// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6MORt4y2WzDHNS6anjU8XboRF5CxFqE0',
    appId: '1:219229493478:web:6d8a682a8035efbba18327',
    messagingSenderId: '219229493478',
    projectId: 'ai-notes-555a6',
    authDomain: 'ai-notes-555a6.firebaseapp.com',
    storageBucket: 'ai-notes-555a6.firebasestorage.app',
    measurementId: 'G-E9PNL7JS6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAchHRoJVVo7rQCFnFBJ_KBRzT-Ni0a9hE',
    appId: '1:219229493478:android:9f0d579f4facce71a18327',
    messagingSenderId: '219229493478',
    projectId: 'ai-notes-555a6',
    storageBucket: 'ai-notes-555a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMZVYaSayqPeNjhTVXQoE9R_pScs0tXno',
    appId: '1:565463920399:ios:ff275a2ac7022c7fae987a',
    messagingSenderId: '565463920399',
    projectId: 'speech-recognition-7d363',
    storageBucket: 'speech-recognition-7d363.firebasestorage.app',
    iosBundleId: 'com.example.lectureNoteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCESxiQAOC5gSZ5JQTGdbMvk0PVZ-xp1Dk',
    appId: '1:565463920399:web:6d3eac9ce972a429ae987a',
    messagingSenderId: '565463920399',
    projectId: 'speech-recognition-7d363',
    authDomain: 'speech-recognition-7d363.firebaseapp.com',
    storageBucket: 'speech-recognition-7d363.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMZVYaSayqPeNjhTVXQoE9R_pScs0tXno',
    appId: '1:565463920399:ios:ff275a2ac7022c7fae987a',
    messagingSenderId: '565463920399',
    projectId: 'speech-recognition-7d363',
    storageBucket: 'speech-recognition-7d363.firebasestorage.app',
    iosBundleId: 'com.example.lectureNoteApp',
  );
}
