// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMvSjLUvmjb5sZqYTN98FFPZgrNxSDvCM',
    appId: '1:446763545044:web:df42fb9c66ff100bc16641',
    messagingSenderId: '446763545044',
    projectId: 'ailecturenote-48907',
    authDomain: 'ailecturenote-48907.firebaseapp.com',
    storageBucket: 'ailecturenote-48907.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpeyyY8S0jUzaxNJNGonsbvOUBLNfDDKc',
    appId: '1:446763545044:android:eca75a05e463b90ac16641',
    messagingSenderId: '446763545044',
    projectId: 'ailecturenote-48907',
    storageBucket: 'ailecturenote-48907.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo4L0Ka0SB5QY5wyUYKTKFThi0agkBFIM',
    appId: '1:446763545044:ios:a3145dc6d7b098f4c16641',
    messagingSenderId: '446763545044',
    projectId: 'ailecturenote-48907',
    storageBucket: 'ailecturenote-48907.appspot.com',
    iosBundleId: 'com.example.lectureNoteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMvSjLUvmjb5sZqYTN98FFPZgrNxSDvCM',
    appId: '1:446763545044:web:dee8ed5a65658373c16641',
    messagingSenderId: '446763545044',
    projectId: 'ailecturenote-48907',
    authDomain: 'ailecturenote-48907.firebaseapp.com',
    storageBucket: 'ailecturenote-48907.appspot.com',
  );
}
