// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCESxiQAOC5gSZ5JQTGdbMvk0PVZ-xp1Dk',
    appId: '1:565463920399:web:ab3f87d07ad3f126ae987a',
    messagingSenderId: '565463920399',
    projectId: 'speech-recognition-7d363',
    authDomain: 'speech-recognition-7d363.firebaseapp.com',
    storageBucket: 'speech-recognition-7d363.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChZ0OO05Aix89IT-OdEjfxHHXZBOniH6o',
    appId: '1:565463920399:android:04d1912f7f95faf4ae987a',
    messagingSenderId: '565463920399',
    projectId: 'speech-recognition-7d363',
    storageBucket: 'speech-recognition-7d363.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMZVYaSayqPeNjhTVXQoE9R_pScs0tXno',
    appId: '1:565463920399:ios:ff275a2ac7022c7fae987a',
    messagingSenderId: '565463920399',
    projectId: 'speech-recognition-7d363',
    storageBucket: 'speech-recognition-7d363.firebasestorage.app',
    iosBundleId: 'com.example.lectureNoteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCESxiQAOC5gSZ5JQTGdbMvk0PVZ-xp1Dk',
    appId: '1:565463920399:web:6d3eac9ce972a429ae987a',
    messagingSenderId: '565463920399',
    projectId: 'speech-recognition-7d363',
    authDomain: 'speech-recognition-7d363.firebaseapp.com',
    storageBucket: 'speech-recognition-7d363.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMZVYaSayqPeNjhTVXQoE9R_pScs0tXno',
    appId: '1:565463920399:ios:ff275a2ac7022c7fae987a',
    messagingSenderId: '565463920399',
    projectId: 'speech-recognition-7d363',
    storageBucket: 'speech-recognition-7d363.firebasestorage.app',
    iosBundleId: 'com.example.lectureNoteApp',
  );

}